### PR TITLE
update summernote + fix issue #20

### PR DESCRIPTION
**Pull request by MichalW**
fix for https://github.com/mpowaga/meteor-autoform-summernote/issues/20

### CODE REVIEW

**Comment by chongwang87** [comment]
+1

**Comment by mariorodriguespt** [comment]
+1

**Comment by abeaudoin2013** [comment]
+1

**Comment by jackkav** [comment]
+1

**Comment by MichalW** [comment]
https://atmospherejs.com/vazco/autoform-summernote

@jackkav @abeaudoin2013  @mariorodriguespt @chongwang87

**Pull request merged**
